backend:
  name: github
  repo: talmage89/blog
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: posts
    label: posts
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: title, name: title, widget: string }
      - { label: date, name: date, widget: datetime }
      - label: tags
        name: tags
        widget: list
        default: []
        hint: one tag per line
      - { label: draft, name: draft, widget: boolean, default: false }
      - { label: body, name: body, widget: markdown }
